### ISSUE TITLE
Unable to install jupyter-plotly-dash

### ISSUE THREAD

**Issue by vinaykumar80** [GibbsConsulting/jupyter-plotly-dash#24]
I tried "pip install jupyter-plotly-dash" and  "pip install jupyter_plotly_dash" but it gives me the following error:
Tried with below configuration:
Python - 3.6 and 3.7
Pip - 18,1 and 19.0.1

Can somebody assist here? Thanks!

Collecting jupyter_plotly_dash
  Using cached https://files.pythonhosted.org/packages/73/74/985284b3709d2ac2cf14d1a890ae61453a035b6193792075c41ca9f55df6/jupyter-plotly-dash-0.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-yrhh1g14/jupyter-plotly-dash/setup.py", line 5, in <module>
        import jupyter_plotly_dash as dpd
      File "/tmp/pip-install-yrhh1g14/jupyter-plotly-dash/jupyter_plotly_dash/__init__.py", line 4, in <module>
        from .dash_wrapper import JupyterDash
      File "/tmp/pip-install-yrhh1g14/jupyter-plotly-dash/jupyter_plotly_dash/dash_wrapper.py", line 1, in <module>
        from .async_views import AsyncViews, get_global_av
      File "/tmp/pip-install-yrhh1g14/jupyter-plotly-dash/jupyter_plotly_dash/async_views.py", line 1, in <module>
        from aiohttp import web
    ModuleNotFoundError: No module named 'aiohttp'

**Comment by GibbsConsulting** [comment]
It looks like the current version available on pypy isn't reporting its dependencies correctly.
Try the command
``pip install nbserverproxy django-plotly-dash jupyter aiohttp``
first, and then follow it with
``pip install jupyter-plotly-dash``
This workaround should deal with the missing dependencies, and not interfere when a future version of the package with the correct dependencies is pushed out.

**Comment by vinaykumar80** [comment]
Thanks, it worked. Also, dash documentation talks about “hot-loading” feature where when code changes in the notebook cell the output will automatically update. I tried changing code but the output was not refreshed until I re-run the cell.

Is this doable with jupyter-plotly-dash?

Thanks!

**Comment by GibbsConsulting** [comment]
Unless I'm missing something, I think that rerunning the cell is the equivalent of hot reloading. When coding, you would choose to save the file at some point, and then hot reloading would cause your changes to be picked up and used. With a notebook, saving the file is replaced with executing the cell.

I suppose in either case one could force things by using a timer in place of waiting for the user to save/recalculate, so that the updates happened periodically, but whilst this should be relatively easy to do its really an IDE/notebook editor feature. And I don't think its a feature I would rush to use!

**Comment by GibbsConsulting** [comment]
Dependencies should now be fixed in 0.2.0 after merge of PR #26

**Comment by vinaykumar80** [comment]
Ok, thanks for merging the dependencies. 

Regarding Hot reloading, I see your point of view. Thank you.
